DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS REBEL;

CREATE TABLE REBEL (
    ID INT IDENTITY NOT NULL PRIMARY KEY,
    AGE INT NOT NULL,
    GENRE VARCHAR(20) NOT NULL,
    LATITUDE INT NOT NULL,
    LOCATION_NAME VARCHAR(50) NOT NULL,
    LONGITUDE INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TRAITOR INT(1),
    TRAITOR_REPORTS INT
);

CREATE TABLE ITEM(
    ID INT IDENTITY NOT NULL PRIMARY KEY,
    ITEM_TYPE VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    REBEL_ID INT NOT NULL,
    CONSTRAINT FK_REBEL_ITEM FOREIGN KEY (REBEL_ID) REFERENCES REBEL(ID)
);